<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>SpartanFitness.com</title>
    <link rel="stylesheet"  href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/7.0.1/css/all.min.css">

    <link rel="stylesheet" href="/style.css">
</head>

<body class="login">
    
   
    <div class="wrapper">
        <form action="">
            <h1> Login </h1>
            <div class="input-box">
                <input type="text" placeholder="Username" required>
            </div>
            <div class="input-box">
                <input type="password" placeholder="Password" required>
            </div>
            
            <div class="remember-forgot">
                <label><input type="checkbox"> Remember me</label>
                <a href="#">Forgot Password?</a>
            </div>
            
            <button type="submit" class="btn">Login</button>
            
            <div class="register-link">
                <p>Don't have an account? 
                    <a href="/customers/signup">Sign Up |</a>
                    <a href="/providers/signup">Register</a></p>
            </div>
        </form>
    </div>
